# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca0bcb79fdb61adde13e7197368a4e07a60898df6073c3a7c05c805bf9d6882a2480f2da934d2b12ae157080861390a1f84706b29dcd0cd79d407ce6776832f8

test:
  secret_key_base: 3b4e1a49b514a32934792d7918f13cb3be8df12be18efd47f183a26446a75b721845f3f5edbcc2a0c026bd75bd632e3140279afdfd5e5daf6a6aaabbceccb4e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
